package com.LabResourceUtilizationPlatform.Entity.Enum;

public enum RoleName {
	SYSTEM_ADMIN,
	INSTITUTION_ADMIN,
	DEPARTMENT_HEAD,
	PROFESSOR,
	ASSOCIATE_PROFESSOR,
	ASSISTANT_PROFESSOR,
	RESEARCH_SCIENTIST,
	RESEARCH_ASSOCIATE,
	LAB_MANAGER,
	LAB_TECHNICIAN,
	RESEARCHER,
	STUDENT
}
